spring:
  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/postgres?schema=url_shortening
    username: postgres
    password: postgres
  redis:
    host: redis
  cache:
    type: redis
    redis:
      time-to-live: 6h
  zipkin:
    base-url: http://192.168.99.100:9411/
    enabled: false
  application:
    name: url-shortening-app

application:
  hashid-salt: "test-salt"
  short-url-domain: "http://localhost:8082/"
  url-range-key: "/counter/url-counter"
  zookeeper:
    base-url: "zookeeper:2181"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httptrace
  metrics:
    export:
      elastic:
        host: http://192.168.99.100:9200
        user-name: elastic
        password: changeme
        enabled: false

server:
  port: 8082
